### PR TITLE
Create horizontal_advection.jl

### LINKED ISSUE #3: Add PPM advection

### PR DESCRIPTION
**Pull request by manozzing**
Fixes #3 
Captures #3

### CODE REVIEW

**Comment by manozzing** [comment]
@ctessum Hmm do you know what happened?

**Comment by manozzing** [comment]
@ctessum Hi Chris, I tried to upload my code (functions in the .jl file) but it has failed. Do you have any idea??

**Comment by ctessum** [comment]
> @ctessum Hi Chris, I tried to upload my code (functions in the .jl file) but it has failed. Do you have any idea??

The red x is say that you haven't signed the contributor license agreement: https://github.com/EarthSciML/EnvironmentalTransport.jl/pull/5#issuecomment-1960404770

If you agree to the agreement, you can type "I have reviewed and hereby sign the CLA" below and then it should turn green

**Comment by manozzing** [comment]
I have reviewed and hereby sign the CLA.

**Comment by ctessum** [comment]
recheck

**Comment by manozzing** [comment]
recheck

**Comment by manozzing** [comment]
I have reviewed and hereby sign the CLA

**Comment by manozzing** [comment]
recheck

**Comment by manozzing** [comment]
Hi Chris! I think now it passed all the tests. Could you confirm to merge this change? Let me know if there is anything I need to do!

**Comment by ctessum** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Wednesday, 08-May-24 22:35:07 UTC` by Gov4Git `dev`

#### Notice `gtveop`
Started managing this PR as Gov4Git proposal `5` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `eaxkzk`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `ge4zcz`
The set of eligible issues claimed by this PR is now empty.

**Review by ctessum — CHANGES_REQUESTED** [review]
The suggestions for this one are the same as for here: https://github.com/EarthSciML/EnvironmentalTransport.jl/pull/8/files

**Comment by ctessum** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Sunday, 21-Jul-24 07:38:56 UTC` by Gov4Git `dev`

#### Notice `n3awnr`
This PR, managed as Gov4Git proposal `5`, has been closed 🎉

The PR approval tally was `0.000000`.

Bounty of `0.000000` credits was donated to the community's matching fund.

Resolved issues:

Rewarded PR reviewers:

Tally breakdown by user:

**Pull request merged**
